### ISSUE TITLE
Please make this repository private

### ISSUE THREAD

**Issue by joey-kilgore** [khill8181/Convert-Infix-to-Postfix#1]
I would strongly recommend making this repository private and only make it public when you are showing it to potential employers. Considering you also include the assignment sheet this is clearly in violation of the "do not share materials of this project or your solution" noted at the end of the project assignment pdf.

**Comment by khill8181** [comment]
Good eye. I'm an idiot. As you can see, I just deleted the post in Discord and will set the appropriate visibility right now.

**Comment by joey-kilgore** [comment]
No worries. Gotta show employers something. Just wanna make sure you don't end up with someone taking your work!
